name: tiffin_ez_01
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  mobile_scanner: ^6.0.10
  permission_handler: ^12.0.0+1
  flutter_dotenv: ^5.2.1
  razorpay_flutter: ^1.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # ✅ Moved here under dev_dependencies

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

# ✅ Placed outside the flutter: section
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
