// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatfnpm install -g @google/gemini-cliorm,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV0j7ylkRR5rEqaOvSKSinRUyBYJ03LTY',
    appId: '1:860690860265:web:8f495cf9311324de9b0878',
    messagingSenderId: '860690860265',
    projectId: 'tiffinez-951e0',
    authDomain: 'tiffinez-951e0.firebaseapp.com',
    storageBucket: 'tiffinez-951e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHvPOYYLilAhM9PV5MALw2Tnm0dlkeUVQ',
    appId: '1:860690860265:android:4463021cc05913049b0878',
    messagingSenderId: '860690860265',
    projectId: 'tiffinez-951e0',
    storageBucket: 'tiffinez-951e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzsiC1-4tutnXHvdmUA0ZF07WLwgZ21Fk',
    appId: '1:860690860265:ios:63048943376d67539b0878',
    messagingSenderId: '860690860265',
    projectId: 'tiffinez-951e0',
    storageBucket: 'tiffinez-951e0.firebasestorage.app',
    iosBundleId: 'com.example.tiffinEz01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzsiC1-4tutnXHvdmUA0ZF07WLwgZ21Fk',
    appId: '1:860690860265:ios:63048943376d67539b0878',
    messagingSenderId: '860690860265',
    projectId: 'tiffinez-951e0',
    storageBucket: 'tiffinez-951e0.firebasestorage.app',
    iosBundleId: 'com.example.tiffinEz01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV0j7ylkRR5rEqaOvSKSinRUyBYJ03LTY',
    appId: '1:860690860265:web:b87222dc42fd21019b0878',
    messagingSenderId: '860690860265',
    projectId: 'tiffinez-951e0',
    authDomain: 'tiffinez-951e0.firebaseapp.com',
    storageBucket: 'tiffinez-951e0.firebasestorage.app',
  );
}
